### ISSUE TITLE
Feh display problem in MONOCLE  mode 

### ISSUE THREAD

**Issue by Asymp** [c00kiemon5ter/monsterwm#22]
When open a picture in feh in MONOCLE  mode, it will be displayed "tiled" to fill the screen.  But it's correct in other mode.

**Comment by c00kiemon5ter** [comment]
not sure why that happens; and not sure what I can do about it
I can reproduce it and it seems kinda random. 
If you put another window on top of feh and then return to feh,
it is fixed, as if feh didn't redraw itself. 

I do have a small idea why it could be tiling the image, same
reason splash screens get tiled, but my guess is that, it'll 
have to be fixed in feh.
