### ISSUE TITLE
transient windows/focus issue

### ISSUE THREAD

**Issue by topcatsoftware** [c00kiemon5ter/monsterwm#3]
Have discovered two issues (2nd issue posted separately). I'll simply explain the steps to reproduce the (mis)behavior...
- open an xterm
- open firefox
- ensure firefox has the focus
- select 'save page as' from the file menu, then cancel saving the page
- the focus is mistakenly given to the xterm rather than firefox which before the transient popup had the focus

**Comment by topcatsoftware** [comment]
update: only appears to happen when firefox is on the left & xterm is on the right...

**Comment by topcatsoftware** [comment]
update: or... firefox is on top & xterm is on bottom...

**Comment by c00kiemon5ter** [comment]
As I said on the forums, that's because the new window gets the last place on the stack area (added as the last client).
After it closes the previous window gets focus, and in your case the previous window from the transient/current is xterm(ie the "new" last window on the stack). 
I, maybe, can fix this for transients, but for spawned windows, I don't think that's possible.
I will look into it

**Comment by c00kiemon5ter** [comment]
wrong issue pointer on that commit, sorry for the fuss. It should close #4 - not this one.

**Comment by topcatsoftware** [comment]
ahh okay.
