### ISSUE TITLE
transient windows/desktop issue

### ISSUE THREAD

**Issue by topcatsoftware** [c00kiemon5ter/monsterwm#4]
- open an xterm
- open firefox and ensure it has the focus
- change to monocle mode
- from the file menu in firefox, select 'save page as'
- cycle through all the desktops till you're back at the desktop you started from...

...only the transient window is shown...

...close it and all other windows must be 'forced' to reappear for instance by invoking grid mode.

Hope this helps (I'm on the verge of switching to monsterwm me thinks you've nailed it), its simple/minimal/robust & chiefly - no-nonsense. Please keep up the good work!

**Comment by c00kiemon5ter** [comment]
This has two parts:
1. you only see the transient window, because on monocle layout, switch back from another desktop would flicker until all windows were visible. To avoid flickering only the current window gets visible.
2. the second part is closing the current window and being left with no others. I fixed this, and will push now. 

I'm not sure what to do with part1 of this. I guess it's not a big issue, cause you only see the 'empty' space only if the window before you switch to another desktop is transient, otherwise the current window will fill the whole screen

**Comment by topcatsoftware** [comment]
Its no big deal...

**Comment by c00kiemon5ter** [comment]
part2 closed by f21fc2c44bfca5d803c96263835ef8fece031fec

**Comment by c00kiemon5ter** [comment]
The new behavior is this:
if you close the current window the previous focused window gets focus. 
if you close again the current window (which is the same as what the previous was) the next gets focused.
If the current window is the last on the stack, the next one is the master window.

**Comment by topcatsoftware** [comment]
On Thu, Jan 5, 2012 at 4:48 PM, Ivan Kanakarakis
reply@reply.github.com
wrote:

> The nrew behavior is this:
> if you close the current window the previous focused window gets focus.
> if you close again the current window (which is the same as what the previous was) the next gets focused.
> If the current window is the last on the stack, the next one is the master window.

Hi Ivan.

Nice. This is a very good way of managing the windows actually. In
fact, it seems you've turned a glitch into a better way of doing
things in my mind.

## 

Later on,
Mike

http://www.topcat.hypermart.net/index.html
