### ISSUE TITLE
Toggle Panel doesn't work on an empty desktop

### ISSUE THREAD

**Issue by firecat53** [c00kiemon5ter/monsterwm#8]
The toggle panel shortcut only seems to work when there is at least one window on the desktop. Minor issue! 

Thanks,
Scott

**Comment by c00kiemon5ter** [comment]
hey,

yeah, that's expected, monsterwm doesn't handle the panel itself, like other windows.
Hidding the panel works by giving the windows the space that the panel uses, so the
windows go on top of the panel, and thus the panel is hidden. 

So, as monsterwm cannot control the panel window (that's because panels either set
the override_redirect flag, or start before the wm) I cannot hide the panel when there is
no other window. dwm on the other hand, draws the panel itself, and thus can control
it, and hide it when no window is on the screen. 

This is also mentioned on the README file.

**Comment by firecat53** [comment]
Ooops...totally missed that!! Sorry to waste your time...thanks for the explanation, though!

Scott

**Comment by c00kiemon5ter** [comment]
no problem ;) don't hesitate to ask anything
